config/routes.rb
Rails.application.routes.draw do
  root 'billboards#index'

  resources :billboards do
    resources :songs
  end


  resources :artists do
    resources :songs
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/billboard.rb
class Billboard < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  belongs_to :billboard
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  

  def index
    @artists = Artist.all
  end

  def show
  end

  def new
    @artist = Artist.new

    render partial: "form"
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to billboard_path(@billboard)
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @artist.update
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_path
  end


  private

  

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name)
  end

end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy]
  
    def index
      @billboards = Billboard.all
    end
  
    def show
    end
  
    def new
      @billboard = Billboard.new
  
      render partial: "form"
    end
  
    def create
      @billboard = Billboard.new(billboard_params)
      if @billboard.save
        redirect_to billboards_path
      else
        render :new
      end
    end
  
    def edit
      render partial: "form"
    end
  
    def update
      if @billboard.update(billboard_params)
        redirect_to billboard_path(@billboard)
      else
        render :edit
      end
  
    end
  
    def destroy
      @billboard.destroy
      redirect_to billboards_path
    end
  
    private
    def set_billboard
      @billboard = Billboard.find(params[:id])
    end
  
    def billboard_params
      params.require(:billboard).permit(:name)
    end
  end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_billboard
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @billboard.songs
  end

  def show

  end

  def new
    @song = @billboard.songs.new
    render partial: "form"
  end

  def create
    @song = @billboard.songs.new(song_params)
    if @song.save
      redirect_to billboard_songs_path(@billboard)
    else
      render :new
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @song.update(song_params)
      redirect_to billboard_song_path(@billboard, @song)
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to billboard_songss_path(@billboard)
  end

  private

  def set_billboard
    @billboard = Billboard.find(params[:billboard_id])
  end

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
params.require(:song).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<h1><%= @artist.id ? 'Edit Artist' : 'Create Artist' %></h1>
<hr />
<%= form_for @artist do |f| %>
    <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>SONGS</h1>


<div class="ui middle aligned animated list">
  <div class="item">
  <i class="angle double right icon"></i>
    <div class="content">
      <a class="header">Drake</a>
      <div class="description"></div>
    </div>
  </div>
  </div>

  <div class="ui middle aligned animated list">
  <div class="item">
  <i class="angle double right icon"></i>
    <div class="content">
      <a class="header">Cardi B</a>
      <div class="description"></div>
    </div>
  </div>
  </div>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/billboards/_form.html.erb
<h1><%= @billboard.id ? 'Edit Billboard' : 'Create Billboard' %></h1>
<hr />
<%= form_for @billboard do |f| %>
    <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Billboards#edit</h1>
<p>Find me in app/views/billboards/edit.html.erb</p>

app/views/billboards/index.html.erb
<h1>Billboards</h1>
<%= link_to "Create New Billboard", new_billboard_path %>
<hr/>
<h3><%= @billboards.length === 0 ? "No Billboards To View!" : "" %></h3>
<ul>
<% @billboards.each do |billboard| %>
    <li> <%= link_to billboard.name, billboard_path(billboard)  %> </li>
    <% end %>
</ul>

app/views/billboards/new.html.erb
<h1>Billboards#new</h1>
<p>Find me in app/views/billboards/new.html.erb</p>

app/views/billboards/show.html.erb
<h1><%= @billboard.name %></h1>
<%= link_to "Delete", billboard_path(@billboard), method: :delete %>
|
<%= link_to "Back", billboards_path %>
|
<%= link_to "Edit", edit_billboard_path(@billboard) %>

<hr />


<h1><%= @billboard.name %> - Songs:</h1>
<%= link_to 'New Song', new_billboard_song_path(@billboard) %>

<ul>
  <% @songs.each do |song| %>

<div class="ui middle aligned animated list">
  <div class="item">
  <i class="angle double right icon"></i>
    <div class="content">
      <a class="header"><%= link_to song.name, billboard_song_path(@billboard, song) %><</a>
      <div class="description"></div>
    </div>
  </div>
  </div>
  <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillboardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <div class="ui container">
    <%= yield %>
  </div>
</html>

app/views/songs/_form.html.erb
<h1><%= @song.id ? 'Edit Song' : 'Create Song' %></h1>
<hr />
<%= form_for @song do |f| %>
    <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>